---
name: "Brew Test"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  brew_error:
    runs-on: macos-latest
    steps:
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: cpp
          tools: https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.17.0/codeql-bundle-osx64.tar.gz
      - name: Brew error
        run: |
          brew install \
            boost \
            cmake \
            miniupnpc \
            node \
            opus \
            pkg-config
