---
name: "Brew Test"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  brew_error:
    runs-on: macos-latest
    steps:
      - name: Brew error
        run: |
          echo "brew install \
            boost \
            cmake \
            miniupnpc \
            node \
            opus \
            pkg-config" > brew_install.sh
          chmod +x brew_install.sh
          ./brew_install.sh
